export const SET_SORT_TYPE = "SET_SORT_TYPE";
export const SET_API_DATA = "SET_API_DATA";
export const DELETE_CHARACTER = "DELETE_CHARACTER";
export const TOGGLE_LIKED = "TOGGLE_LIKED";
export const SET_SEARCH_TERM = "SET_SEARCH_NAME";
